config/routes.rb
Xpeos::Application.routes.draw do

  resources :xp_users do
  	collection do
  		get :export
  	end
  end

  resources :participants do
  	collection do
  		get :export
  	end
  end

  

  root 'participants#new'
  
  

  

end

app/models/participant.rb
# encoding: utf-8
class Participant < ActiveRecord::Base
	
	validates_presence_of :name, :message => '請輸入您的名字'
	validates_presence_of :phone, :message => '請輸入您的聯絡電話'
	
	validates_presence_of :email, :message => '請輸入您的電子信箱'
	validates_format_of :email, :with => /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i, :message => "請輸入正確的電子信箱格式"
	
	validates_presence_of :address, :message => '請輸入您的住址'
	validates_presence_of :key, :message => '請輸入您購買的產品識別碼'
	validates_format_of :key, :with => /\A\w{5}\-\w{5}\-\w{5}\-\w{5}\z/i, :message => '產品識別碼格式有誤，請重新檢查'
	
	validates_presence_of :product, :message => '請勾選您購買的產品類別'
	validates_presence_of :extra, :message => '請勾選購買廠牌', :if => :check_product?
	validates_presence_of :extra_product, :message => '請輸入購買的產品型號', :if => :check_product?

	def check_product?
		self.product.match('Windows 8.1 網路購買盒裝版序號').nil?
	end
end

app/models/xp_user.rb
class XpUser < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/participants_controller.rb
# encoding: utf-8
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_download, only: [:export]


  def export
  	@participants = Participant.order( :created_at => :desc )
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)
    
    @participant.ip = request.remote_ip
    
    respond_to do |format|
      if @participant.save
        format.html { redirect_to new_participant_path, notice: '我們收到您的資料囉，感謝您的參與，也祝您中獎！' }

      else

      	flash[ :warning ] = @participant.errors.values.flatten.join('<br />')
      
        format.html { render action: 'new' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :phone, :email, :address, :key, :product, :extra, :extra_brand, :extra_product, :cpu)
    end
    
    def authenticate_download
    
    	if request.remote_ip != '127.0.0.1' && request.remote_ip != '220.133.14.87'
    		puts 'ip 不允許，跳離。'
    		redirect_to root_url
    	end
    
    	authenticate_or_request_with_http_basic do |username, password|
    	  if Digest::SHA1.hexdigest( username ) == 'c34ff016869b9f77e92064651c867f1eee8cb506' && Digest::SHA1.hexdigest( password ) == 'fae787a2334dd261e3344e7ff59d0230f0259ef6'    	  
    	  	true
    	  else
    	  	session[ :try_download ] = session[ :try_download ].nil? ? 0 : session[ :try_download ]+1
    	  	
    	  	if session[ :try_download ] > 5
    	  		redirect_to root_url
    	  	end    	  	
    	  end
	    end
    end
    
end

app/controllers/xp_users_controller.rb
# encoding: utf-8
class XpUsersController < ApplicationController
  before_action :set_xp_user, only: [:show, :edit, :update, :destroy]
  before_filter :allow_iframe_requests
  before_filter  :set_p3p, only: [ :new, :create ]

  before_filter :authenticate_download, only: [:export]


  layout false

  # GET /xp_users/new
  def new
    @xp_user = XpUser.new
  end

  
  def export
  	@xp_users = XpUser.order( :created_at => :desc )
  end


  # POST /xp_users
  # POST /xp_users.json
  def create
    @xp_user = XpUser.new(xp_user_params)

    respond_to do |format|
      if @xp_user.save
        format.html { redirect_to new_xp_user_path, notice: '恭喜您已經成功取得抽獎資格，請繼續注意本網站公告喔！' }
        format.json { render action: 'show', status: :created, location: @xp_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @xp_user.errors, status: :unprocessable_entity }
      end
    end
  end


  def allow_iframe_requests
	response.headers['X-Frame-Options'] = "ALLOW"
  end

	def set_p3p
	  response.headers["P3P"]='CP="CAO PSA OUR"'
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xp_user
      @xp_user = XpUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xp_user_params
      params.require(:xp_user).permit(:name, :phone, :email, :address, :fb_user_id, :fb_share_id, :access_token)
    end
    
    
    def authenticate_download
    
    	if request.remote_ip != '127.0.0.1' && request.remote_ip != '220.133.14.87'
    		puts 'ip 不允許，跳離。'
    		redirect_to root_url
    	end
    
    	authenticate_or_request_with_http_basic do |username, password|
    	  if Digest::SHA1.hexdigest( username ) == 'c34ff016869b9f77e92064651c867f1eee8cb506' && Digest::SHA1.hexdigest( password ) == 'fae787a2334dd261e3344e7ff59d0230f0259ef6'    	  
    	  	true
    	  else
    	  	session[ :try_download ] = session[ :try_download ].nil? ? 0 : session[ :try_download ]+1
    	  	
    	  	if session[ :try_download ] > 5
    	  		redirect_to root_url
    	  	end    	  	
    	  end
	    end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/xp_users_helper.rb
module XpUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="Robots" content="index,follow"/>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="Robots" content="index,follow"/>
<meta name="ms.locale" content="zh-tw">
<meta name="WT.sp" content="_taiwan_promo_windows_xpto8_" />
<meta name="WT.z_locale" content="zh-tw"/ >
<meta name="keywords" content="XP,win xp,win 7,win 8,win 8.1,Windows XP,Windows 7,Windows 8,Windows 8.1,XP 終止支援,XP EOS,Windows 作業系統,升級 windows 8,迎春改運歡送 XP,微軟,台灣微軟,Microsoft"/>
<title>歡送 XP 換 Windows 8.1，馬上抽大獎拿好禮</title>
<meta name="description" content="送走 Window XP，告別老舊作業系統不合時宜問題，立刻享受Windows 8.1 全新功能，再抽無線伊萊克斯、變形平板，還有更多優惠好康" />
<meta property="og:site_name" content="XP 除舊換新優惠活動"/>
<meta property="og:title" content="歡送 Windows XP 迎接 Windows 8.1，送舊迎新拿大獎抽好禮"/>
<meta property="og:description" content="送走 Window XP，告別老舊作業系統不合時宜問題，立刻享受 Windows 8.1 全新功能，再抽無線伊萊克斯、變形平板，還有更多優惠好康"/>
<meta property="og:type" content="website"/>
<meta name="DC.Rights" content="台灣微軟"/>
<meta name="DC.Date" content="2014/01/21"/>
<meta name="DC.Language" scheme="W3CDTF" content="zh-TW"/>
<meta name="DC.Subject" content="歡送 XP 換 Windows 8.1，馬上抽大獎拿好禮"/>
<meta name="DC.Type" content="活動"/>
<meta property="og:image" content="http://park.summers.com.tw/toto/xpeos_2/images/thumb.jpg">
<link rel="image_src" href="http://park.summers.com.tw/toto/xpeos_2/images/thumb.jpg">


  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<script>
	if ( window.location.href.match(/xpeos.midsummer.me/)) {
		window.location.href = 'http://www.microsoft.com/taiwan/promo/windows/xpto8/';
	}
</script>

<link rel="stylesheet" href="<%= root_url %>/css/reset.css">
<link rel="stylesheet" href="<%= root_url %>/css/form.css">
<script src="<%= root_url %>/js/jquery-1.10.2.min.js"></script>
<script src="<%= root_url %>/js/auto-full-height.min.js"></script>


</head>

<body>


<script type="text/JavaScript">
var varSegmentation=0;
var varClickTracking=1;
var varCustomerTracking=1;
var varAutoFirePV=1;
var Route="59550";
document.write("<script type='text/javascript' src='" +
(window.location.protocol) + "//c.microsoft.com/ms.js'" + "><\/script>");
</script>
<noscript><img alt="" width="1" height="1" src="http://c.microsoft.com/trans_pixel.aspx" /></noscript>

<div id="wrapper">
  <div id="article">
  	<%= yield %>
    
  </div>
  <div id="footer"> ©  2014 Microsoft Corporation. 著作權所有，並保留一切權利。<a href="http://www.microsoft.com/taiwan/misc/cpyright.htm" target="_blank">使用規定</a>｜<a href="http://www.microsoft.com/library/toolbar/3.0/trademarks/zh-tw.mspx" target="_blank">商標</a>｜<a href="http://www.microsoft.com/privacystatement/zh-tw/core/default.aspx" target="_blank">隱私權聲明</a> </div>
</div>
</body>
</html>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">姓名</Data></Cell>
        <Cell><Data ss:Type="String">電話</Data></Cell>
        <Cell><Data ss:Type="String">電子信箱</Data></Cell>
        <Cell><Data ss:Type="String">地址</Data></Cell>
        <Cell><Data ss:Type="String">序號</Data></Cell>
        <Cell><Data ss:Type="String">作業系統版本</Data></Cell>
        <Cell><Data ss:Type="String">購買品牌</Data></Cell>
        <Cell><Data ss:Type="String">購買產品</Data></Cell>
        <Cell><Data ss:Type="String">選購CPU</Data></Cell>
        <Cell><Data ss:Type="String">時間</Data></Cell>
      </Row>
    <% @participants.each do |participants| %>
      <Row>
        <Cell><Data ss:Type="String"><%= participants.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.phone %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.address %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.key %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.product %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.extra %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.extra_product.nil? ? participants.extra_brand : participants.extra_product %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.cpu %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participants.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th>Key</th>
      <th>Products</th>
      <th>Extra</th>
      <th>Cpu</th>
      <th>Ip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.phone %></td>
        <td><%= participant.email %></td>
        <td><%= participant.address %></td>
        <td><%= participant.key %></td>
        <td><%= participant.product %></td>
        <td><%= participant.extra %></td>
        <td><%= participant.cpu %></td>
        <td><%= participant.ip %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<!-- 

<script>
<% if flash[ :notice ] %>
	alertify.alert('<%= flash[ :notice ].html_safe %>')
	<% flash.delete(:notice) %>
<% end %>
<% if flash[ :warning ] %>
	alertify.alert('<%= flash[ :warning ].html_safe %>')
	<% flash.delete(:warning) %>
<% end %>
</script>

<%= form_for(@participant) do |f| %>
<h2><img src="<%= root_url %>images/f-03.png"/></h2>
<div id="content-1"> <span id="note-1">請確實填寫正確資料，以便中奬通知 <b>以下紅線範圍為必填資料</b></span> <span id="note-2"><b>*中獎者須配合主辦單位要求，提供產品序號、發票等相關購買證明</b></span>
  <div id="table-1">
    <div class="table-box">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th width="17%" align="right"><%= f.label :name, '真實姓名' %></th>
          <td width="83%"><%= f.text_field :name, :class => "text" %></td>
        </tr>
      </table>
    </div>
    <div class="table-box">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th width="17%" align="right"><%= f.label :phone, '聯絡電話' %></th>
          <td width="83%"><%= f.text_field :phone, :class => "text" %></td>
        </tr>
      </table>
    </div>
    <div class="table-box">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th width="17%" align="right"><%= f.label :email, '電子信箱' %></th>
          <td width="83%"><%= f.text_field :email, :class => "text" %></td>
        </tr>
      </table>
    </div>
    <div class="table-box">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th width="17%" align="right"><%= f.label :address, '收件地址' %></th>
          <td width="83%"><%= f.text_field :address, :class => "text" %></td>
        </tr>
      </table>
    </div>
    <div class="table-box">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th width="17%" align="right"><%= f.label :key, '產品識別碼' %></th>
          <td width="83%"><%= f.text_field :key, :class => "text", :maxlength => 23 %></td>
        </tr>
      </table>
    </div>
    <span>Windows 8 產品識別碼 (PID) 20 位英文加數字混和碼，填寫格式為 00000-00000-00000-00000 <a target="_blank" href="http://www.microsoft.com/taiwan/promo/windows-8-offer/find_pid.htm">識別碼教學</a></span> </div>
  <div id="table-2">
    <h3>Windows 8 購買版本</h3>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><input name="participant[product]" type="checkbox" value="Windows 8" class="checkbox"/>
          Windows 8</td>
        <td><input name="participant[product]" type="checkbox" value="Windows 8 專業版" class="checkbox"/>
          Windows 8 專業版</td>
        <td><input name="participant[product]" type="checkbox" value="Windows 8 隨機版" class="checkbox"/>
          Windows 8 隨機版</td>
        <td><input name="participant[product]" type="checkbox" value="Windows 8 網路升級版" class="checkbox"/>
          Windows 8 網路升級版</td>
      </tr>
      <tr>
        <td><input name="participant[product]" type="checkbox" value="Windows 8.1" class="checkbox"/>
          Windows 8.1</td>
        <td><input name="participant[product]" type="checkbox" value="Windows 8.1 專業版" class="checkbox"/>
          Windows 8.1 專業版</td>
        <td><input name="participant[product]" type="checkbox" value="Windows 8.1 隨機版" class="checkbox"/>
          Windows 8.1 隨機版</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td colspan="2"><input name="participant[product]" type="checkbox" value="Windows 8.1 網路購買盒裝版序號" class="checkbox"/>
          Windows 8.1 網路購買盒裝版序號</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </div>
  <div id="table-3">
    <h3>參加雙 A 大廠「享好禮．加碼抽」請勾選購買廠牌及型號：</h3>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="13%"><input name="participant[extra]" type="checkbox" value="Acer" class="checkbox"/>
          Acer</td>
        <td width="14%"><input name="participant[extra]" type="checkbox" value="ASUS" class="checkbox"/>
          ASUS</td>
        <td width="8%"><input id="extra-else" name="participant[extra]" type="checkbox" value="其他" class="checkbox"/>
          其他</td>
        <td width="27%"><%= f.text_field :extra_brand, :disabled => 'disabled', :id => 'extra-else-bland', :class => "text" %></td>
        <td width="11%">購買型號：</td>
        <td width="27%"><%= f.text_field :extra_product, :class => "text", :class => 'text' %></td>
      </tr>
    </table>
  </div>
</div>
<div id="content-2">
  <h3>演唱會貴賓早鳥優惠   資料登錄</h3>
  <div class="left"> 購買 Intel 指定處理器，參加 Intel X 蔡依林菜市場名<br>
    同樂會演唱會入場劵抽獎</div>
  <div class="right">
  <div class="table-box">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th width="40%">購買處理器</th>
        <td width="60%">
        	<%= f.select :cpu, [['- 請選擇處理器 -', ''], 'Intel® Core™', 'Intel® Pentium®', 'Intel® Celeron®', 'Intel® Atom™', '其他' ] %>
        </td>
      </tr>
    </table>
    </div>
  </div>
</div>
<div id="content-3">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="4%" valign="top"><input id="agree_private_announce" name="" type="checkbox" value="[我同意隱私權聲明]" class="checkbox"/></td>
      <td width="96%">我同意<br>
        若您同意本公司依下述聲明使用您的個人資料，請勾選左側方格隱私權聲明：參加者同意所提供的姓名、電子郵件地址、一般郵寄地址或聯絡電話，得由主辦單位及其指定之執行單位或承攬第三人，基於辦理本活動之目的予以蒐集、處理及利用。利用期間為本活動期間及本活動辦理完畢為止，利用地區為台灣。您得自由選擇是否提供個人資料時，但若不提供，則主辦單位無法給予有效參加資格，亦無法履行提供獎項的義務。您就所提供的個人資料得要求查詢、閱覽、製給複製本、補充、更正、刪除、或停止蒐集、處理或利用。</td>
    </tr>
    <tr>
      <td colspan="2" align="right"><input name="" type="reset" data-confirm="確定清空您已經填寫的資料？" class="button" id="button-1" value="" />
      <%= f.submit '', :class=> 'button', :id => 'button-2' %>
    </tr>
  </table>
</div>
<% end %>


<script>
	$(':checkbox').click(function(){ 
		$(':checkbox[name="' + $(this).attr('name') + '"]').not($(this)).attr('checked', false); 		
		
		if ( $('#extra-else').prop('checked') ) {
			$('#extra-else-bland').attr('disabled', false);
		} else {
			$('#extra-else-bland').attr('disabled', true);			
		}
	})
	
	$('th').has('.field_with_errors').addClass('column_with_errors');
	
	<% if !@participant.product.nil? && @participant.product.length > 0 %>
		$('input[value="<%= @participant.product %>"]').click();
	<% end %>
	
	<% if !@participant.extra.nil? && @participant.extra.length > 0 %>
		$('input[value="<%= @participant.extra %>"]').click();
	<% end %>
	
	$('#new_participant').submit(function() {
		
		if (!$('#agree_private_announce').prop('checked')) {
			alertify.alert('您必須同意隱私權聲明才可以加活動喔！');
			return false;
		}
		
		
	});
	
	
	$('#participant_key').keyup(function() {
		var value = $(this).val();
		var sets = value.split('-');
		
		var last = sets.pop();
		
		if ( last.length > 5 ) {
			sets.push( last.substr(0, 5) );
			sets.push( last.substr(5, last.length) )
		} else {
			sets.push(last);
		}
		
		$(this).val( sets.join('-') );
		
	});
	
</script>

-->

<h1>本次活動已結束，非常謝謝您的參與！</h1>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @participant.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @participant.address %>
</p>

<p>
  <strong>Key:</strong>
  <%= @participant.key %>
</p>

<p>
  <strong>Products:</strong>
  <%= @participant.product %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @participant.extra %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @participant.extra_product %>
</p>


<p>
  <strong>Cpu:</strong>
  <%= @participant.cpu %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @participant.ip %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/xp_users/_form.html.erb
<%= form_for(@xp_user) do |f| %>
  <% if @xp_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xp_user.errors.count, "error") %> prohibited this xp_user from being saved:</h2>

      <ul>
      <% @xp_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :fb_user_id %><br>
    <%= f.text_field :fb_user_id %>
  </div>
  <div class="field">
    <%= f.label :fb_share_id %><br>
    <%= f.text_field :fb_share_id %>
  </div>
  <div class="field">
    <%= f.label :access_token %><br>
    <%= f.text_field :access_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xp_users/edit.html.erb
<h1>Editing xp_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @xp_user %> |
<%= link_to 'Back', xp_users_path %>

app/views/xp_users/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">姓名</Data></Cell>
        <Cell><Data ss:Type="String">電話</Data></Cell>
        <Cell><Data ss:Type="String">電子信箱</Data></Cell>
        <Cell><Data ss:Type="String">時間</Data></Cell>
      </Row>
    <% @xp_users.each do |xp_user| %>
      <Row>
        <Cell><Data ss:Type="String"><%= xp_user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xp_user.phone %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xp_user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xp_user.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/xp_users/index.html.erb
<div class="fb-like" data-send="true" data-width="450" data-show-faces="true"></div>

<h1>Listing xp_users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th>Fb user</th>
      <th>Fb share</th>
      <th>Access token</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @xp_users.each do |xp_user| %>
      <tr>
        <td><%= xp_user.name %></td>
        <td><%= xp_user.phone %></td>
        <td><%= xp_user.email %></td>
        <td><%= xp_user.address %></td>
        <td><%= xp_user.fb_user_id %></td>
        <td><%= xp_user.fb_share_id %></td>
        <td><%= xp_user.access_token %></td>
        <td><%= link_to 'Show', xp_user %></td>
        <td><%= link_to 'Edit', edit_xp_user_path(xp_user) %></td>
        <td><%= link_to 'Destroy', xp_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xp user', new_xp_user_path %>

app/views/xp_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @xp_user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @xp_user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @xp_user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @xp_user.address %>
</p>

<p>
  <strong>Fb user:</strong>
  <%= @xp_user.fb_user_id %>
</p>

<p>
  <strong>Fb share:</strong>
  <%= @xp_user.fb_share_id %>
</p>

<p>
  <strong>Access token:</strong>
  <%= @xp_user.access_token %>
</p>

<%= link_to 'Edit', edit_xp_user_path(@xp_user) %> |
<%= link_to 'Back', xp_users_path %>